typography_spectrum: 0.50995
color:
  brandColors:
    - '#010101'
    - '#626262'
    - '#b2b2b2'
    - '#a10006'
    - '#eaeaea'
  brandStrength: 0
  lightness: 0.2204301
  saturation: 0.9375
  rhythmicContrast: 1
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/d2359f48-bb53-49f2-85f6-33875c3b7f8b.jpg
  type: website
  appId: null
layout_spectrum: 0.67854
analytics:
  google: null
  facebook: null
  twitter: null
name: beautifullife
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - name: Maxim
    url: 'http://www.maxim.com/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Beautiful Life
description: breathe and relax
purpose: []
