name: nicethings
favicon: null
layout_spectrum: 0.5646904020104557
typography_spectrum: 0.7739544627256691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.14415603037923574
  lightness: 0.6374180887360126
  saturation: 0.15193437598645687
  rhythmicContrast: 0.008631439181044698
purpose: []
