name: nicethings
favicon: null
layout_spectrum: 0.75069
typography_spectrum: 0.7739544627256691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#626262'
    - '#b2b2b2'
    - '#a10006'
    - '#eaeaea'
  brandStrength: 0.5
  lightness: 0.6374180887360126
  saturation: 0.15193437598645687
  rhythmicContrast: 0.5
purpose: []
