name: nicethings
favicon: null
layout_spectrum: 0.75069
typography_spectrum: 0.7739544627256691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070302'
    - '#33383b'
    - '#f6e9e3'
    - '#e6a390'
    - '#748893'
  brandStrength: 0.5
  lightness: 0.6374180887360126
  saturation: 0.15193437598645687
  rhythmicContrast: 0.008631439181044698
purpose: []
