name: nicethings
favicon: null
layout_spectrum: 0.77469
typography_spectrum: 0.50995
title: Nice Things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#626262'
    - '#b2b2b2'
    - '#a10006'
    - '#eaeaea'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
